# Generated by Django 5.1 on 2024-10-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesworks', '0005_remove_task_updated_date_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='User',
            new_name='user',
        ),
    ]
